// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.1
// source: com_season.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BoxMonsterInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	BoxType         *BoxType               `protobuf:"varint,1,opt,name=box_type,json=boxType,enum=Next.BoxType" json:"box_type,omitempty"`
	IsShiny         *bool                  `protobuf:"varint,2,opt,name=is_shiny,json=isShiny" json:"is_shiny,omitempty"`
	IsFantastic     *bool                  `protobuf:"varint,3,opt,name=is_fantastic,json=isFantastic" json:"is_fantastic,omitempty"`
	BoxConfId       *uint32                `protobuf:"varint,4,opt,name=box_conf_id,json=boxConfId" json:"box_conf_id,omitempty"`
	PetContentId    *int32                 `protobuf:"varint,5,opt,name=pet_content_id,json=petContentId" json:"pet_content_id,omitempty"`
	IsNightmare     *bool                  `protobuf:"varint,6,opt,name=is_nightmare,json=isNightmare" json:"is_nightmare,omitempty"`
	BelongSeason    *int32                 `protobuf:"varint,7,opt,name=belong_season,json=belongSeason" json:"belong_season,omitempty"`
	Name            []byte                 `protobuf:"bytes,8,opt,name=name" json:"name,omitempty"`
	MonsterId       *uint32                `protobuf:"varint,9,opt,name=monster_id,json=monsterId" json:"monster_id,omitempty"`
	PetRarityType   *PetRarityType         `protobuf:"varint,10,opt,name=pet_rarity_type,json=petRarityType,enum=Next.PetRarityType" json:"pet_rarity_type,omitempty"`
	PetMutationType *PetMutationType       `protobuf:"varint,11,opt,name=pet_mutation_type,json=petMutationType,enum=Next.PetMutationType" json:"pet_mutation_type,omitempty"`
	PetNature       *int32                 `protobuf:"varint,12,opt,name=pet_nature,json=petNature" json:"pet_nature,omitempty"`
	Gender          *uint32                `protobuf:"varint,13,opt,name=gender" json:"gender,omitempty"`
	Height          *int32                 `protobuf:"varint,14,opt,name=height" json:"height,omitempty"`
	Weight          *int32                 `protobuf:"varint,15,opt,name=weight" json:"weight,omitempty"`
	Voice           *int32                 `protobuf:"varint,16,opt,name=voice" json:"voice,omitempty"`
	NameSrc         *PetNameSource         `protobuf:"varint,17,opt,name=name_src,json=nameSrc,enum=dataconfig.PetNameSource" json:"name_src,omitempty"`
	RefreshBatchId  *uint64                `protobuf:"varint,30,opt,name=refresh_batch_id,json=refreshBatchId" json:"refresh_batch_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BoxMonsterInfo) Reset() {
	*x = BoxMonsterInfo{}
	mi := &file_com_season_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoxMonsterInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoxMonsterInfo) ProtoMessage() {}

func (x *BoxMonsterInfo) ProtoReflect() protoreflect.Message {
	mi := &file_com_season_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoxMonsterInfo.ProtoReflect.Descriptor instead.
func (*BoxMonsterInfo) Descriptor() ([]byte, []int) {
	return file_com_season_proto_rawDescGZIP(), []int{0}
}

func (x *BoxMonsterInfo) GetBoxType() BoxType {
	if x != nil && x.BoxType != nil {
		return *x.BoxType
	}
	return BoxType_BOX_TYPE_INVALID
}

func (x *BoxMonsterInfo) GetIsShiny() bool {
	if x != nil && x.IsShiny != nil {
		return *x.IsShiny
	}
	return false
}

func (x *BoxMonsterInfo) GetIsFantastic() bool {
	if x != nil && x.IsFantastic != nil {
		return *x.IsFantastic
	}
	return false
}

func (x *BoxMonsterInfo) GetBoxConfId() uint32 {
	if x != nil && x.BoxConfId != nil {
		return *x.BoxConfId
	}
	return 0
}

func (x *BoxMonsterInfo) GetPetContentId() int32 {
	if x != nil && x.PetContentId != nil {
		return *x.PetContentId
	}
	return 0
}

func (x *BoxMonsterInfo) GetIsNightmare() bool {
	if x != nil && x.IsNightmare != nil {
		return *x.IsNightmare
	}
	return false
}

func (x *BoxMonsterInfo) GetBelongSeason() int32 {
	if x != nil && x.BelongSeason != nil {
		return *x.BelongSeason
	}
	return 0
}

func (x *BoxMonsterInfo) GetName() []byte {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *BoxMonsterInfo) GetMonsterId() uint32 {
	if x != nil && x.MonsterId != nil {
		return *x.MonsterId
	}
	return 0
}

func (x *BoxMonsterInfo) GetPetRarityType() PetRarityType {
	if x != nil && x.PetRarityType != nil {
		return *x.PetRarityType
	}
	return PetRarityType_PET_RARITY_TYPE_INVALID
}

func (x *BoxMonsterInfo) GetPetMutationType() PetMutationType {
	if x != nil && x.PetMutationType != nil {
		return *x.PetMutationType
	}
	return PetMutationType_PET_MUTATION_TYPE_INVALID
}

func (x *BoxMonsterInfo) GetPetNature() int32 {
	if x != nil && x.PetNature != nil {
		return *x.PetNature
	}
	return 0
}

func (x *BoxMonsterInfo) GetGender() uint32 {
	if x != nil && x.Gender != nil {
		return *x.Gender
	}
	return 0
}

func (x *BoxMonsterInfo) GetHeight() int32 {
	if x != nil && x.Height != nil {
		return *x.Height
	}
	return 0
}

func (x *BoxMonsterInfo) GetWeight() int32 {
	if x != nil && x.Weight != nil {
		return *x.Weight
	}
	return 0
}

func (x *BoxMonsterInfo) GetVoice() int32 {
	if x != nil && x.Voice != nil {
		return *x.Voice
	}
	return 0
}

func (x *BoxMonsterInfo) GetNameSrc() PetNameSource {
	if x != nil && x.NameSrc != nil {
		return *x.NameSrc
	}
	return PetNameSource_PNS_PET_BASE
}

func (x *BoxMonsterInfo) GetRefreshBatchId() uint64 {
	if x != nil && x.RefreshBatchId != nil {
		return *x.RefreshBatchId
	}
	return 0
}

type SeasonPetInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IsNightmare    *bool                  `protobuf:"varint,1,opt,name=is_nightmare,json=isNightmare" json:"is_nightmare,omitempty"`
	IsShiny        *bool                  `protobuf:"varint,2,opt,name=is_shiny,json=isShiny" json:"is_shiny,omitempty"`
	IsFantastic    *bool                  `protobuf:"varint,3,opt,name=is_fantastic,json=isFantastic" json:"is_fantastic,omitempty"`
	MixBlood       *int32                 `protobuf:"varint,4,opt,name=mix_blood,json=mixBlood" json:"mix_blood,omitempty"`
	DeleteTime     *uint32                `protobuf:"varint,5,opt,name=delete_time,json=deleteTime" json:"delete_time,omitempty"`
	RefreshBatchId *uint64                `protobuf:"varint,20,opt,name=refresh_batch_id,json=refreshBatchId" json:"refresh_batch_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SeasonPetInfo) Reset() {
	*x = SeasonPetInfo{}
	mi := &file_com_season_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeasonPetInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeasonPetInfo) ProtoMessage() {}

func (x *SeasonPetInfo) ProtoReflect() protoreflect.Message {
	mi := &file_com_season_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeasonPetInfo.ProtoReflect.Descriptor instead.
func (*SeasonPetInfo) Descriptor() ([]byte, []int) {
	return file_com_season_proto_rawDescGZIP(), []int{1}
}

func (x *SeasonPetInfo) GetIsNightmare() bool {
	if x != nil && x.IsNightmare != nil {
		return *x.IsNightmare
	}
	return false
}

func (x *SeasonPetInfo) GetIsShiny() bool {
	if x != nil && x.IsShiny != nil {
		return *x.IsShiny
	}
	return false
}

func (x *SeasonPetInfo) GetIsFantastic() bool {
	if x != nil && x.IsFantastic != nil {
		return *x.IsFantastic
	}
	return false
}

func (x *SeasonPetInfo) GetMixBlood() int32 {
	if x != nil && x.MixBlood != nil {
		return *x.MixBlood
	}
	return 0
}

func (x *SeasonPetInfo) GetDeleteTime() uint32 {
	if x != nil && x.DeleteTime != nil {
		return *x.DeleteTime
	}
	return 0
}

func (x *SeasonPetInfo) GetRefreshBatchId() uint64 {
	if x != nil && x.RefreshBatchId != nil {
		return *x.RefreshBatchId
	}
	return 0
}

type LineBallMonsterInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	IsShiny         *bool                  `protobuf:"varint,1,opt,name=is_shiny,json=isShiny" json:"is_shiny,omitempty"`
	IsFantastic     *bool                  `protobuf:"varint,2,opt,name=is_fantastic,json=isFantastic" json:"is_fantastic,omitempty"`
	IsNightmare     *bool                  `protobuf:"varint,3,opt,name=is_nightmare,json=isNightmare" json:"is_nightmare,omitempty"`
	PetContentId    *int32                 `protobuf:"varint,4,opt,name=pet_content_id,json=petContentId" json:"pet_content_id,omitempty"`
	BelongSeason    *int32                 `protobuf:"varint,5,opt,name=belong_season,json=belongSeason" json:"belong_season,omitempty"`
	PetSpecialityId *int32                 `protobuf:"varint,6,opt,name=pet_speciality_id,json=petSpecialityId" json:"pet_speciality_id,omitempty"`
	PetTalentRank   *int32                 `protobuf:"varint,7,opt,name=pet_talent_rank,json=petTalentRank" json:"pet_talent_rank,omitempty"`
	MixBlood        *int32                 `protobuf:"varint,8,opt,name=mix_blood,json=mixBlood" json:"mix_blood,omitempty"`
	RefreshBatchId  *uint64                `protobuf:"varint,20,opt,name=refresh_batch_id,json=refreshBatchId" json:"refresh_batch_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *LineBallMonsterInfo) Reset() {
	*x = LineBallMonsterInfo{}
	mi := &file_com_season_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LineBallMonsterInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LineBallMonsterInfo) ProtoMessage() {}

func (x *LineBallMonsterInfo) ProtoReflect() protoreflect.Message {
	mi := &file_com_season_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LineBallMonsterInfo.ProtoReflect.Descriptor instead.
func (*LineBallMonsterInfo) Descriptor() ([]byte, []int) {
	return file_com_season_proto_rawDescGZIP(), []int{2}
}

func (x *LineBallMonsterInfo) GetIsShiny() bool {
	if x != nil && x.IsShiny != nil {
		return *x.IsShiny
	}
	return false
}

func (x *LineBallMonsterInfo) GetIsFantastic() bool {
	if x != nil && x.IsFantastic != nil {
		return *x.IsFantastic
	}
	return false
}

func (x *LineBallMonsterInfo) GetIsNightmare() bool {
	if x != nil && x.IsNightmare != nil {
		return *x.IsNightmare
	}
	return false
}

func (x *LineBallMonsterInfo) GetPetContentId() int32 {
	if x != nil && x.PetContentId != nil {
		return *x.PetContentId
	}
	return 0
}

func (x *LineBallMonsterInfo) GetBelongSeason() int32 {
	if x != nil && x.BelongSeason != nil {
		return *x.BelongSeason
	}
	return 0
}

func (x *LineBallMonsterInfo) GetPetSpecialityId() int32 {
	if x != nil && x.PetSpecialityId != nil {
		return *x.PetSpecialityId
	}
	return 0
}

func (x *LineBallMonsterInfo) GetPetTalentRank() int32 {
	if x != nil && x.PetTalentRank != nil {
		return *x.PetTalentRank
	}
	return 0
}

func (x *LineBallMonsterInfo) GetMixBlood() int32 {
	if x != nil && x.MixBlood != nil {
		return *x.MixBlood
	}
	return 0
}

func (x *LineBallMonsterInfo) GetRefreshBatchId() uint64 {
	if x != nil && x.RefreshBatchId != nil {
		return *x.RefreshBatchId
	}
	return 0
}

type StarRockShellInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MonsterId      *uint32                `protobuf:"varint,1,opt,name=monster_id,json=monsterId" json:"monster_id,omitempty"`
	BaseConfId     *uint32                `protobuf:"varint,2,opt,name=base_conf_id,json=baseConfId" json:"base_conf_id,omitempty"`
	HasShinyReward *bool                  `protobuf:"varint,3,opt,name=has_shiny_reward,json=hasShinyReward" json:"has_shiny_reward,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StarRockShellInfo) Reset() {
	*x = StarRockShellInfo{}
	mi := &file_com_season_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StarRockShellInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StarRockShellInfo) ProtoMessage() {}

func (x *StarRockShellInfo) ProtoReflect() protoreflect.Message {
	mi := &file_com_season_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StarRockShellInfo.ProtoReflect.Descriptor instead.
func (*StarRockShellInfo) Descriptor() ([]byte, []int) {
	return file_com_season_proto_rawDescGZIP(), []int{3}
}

func (x *StarRockShellInfo) GetMonsterId() uint32 {
	if x != nil && x.MonsterId != nil {
		return *x.MonsterId
	}
	return 0
}

func (x *StarRockShellInfo) GetBaseConfId() uint32 {
	if x != nil && x.BaseConfId != nil {
		return *x.BaseConfId
	}
	return 0
}

func (x *StarRockShellInfo) GetHasShinyReward() bool {
	if x != nil && x.HasShinyReward != nil {
		return *x.HasShinyReward
	}
	return false
}

type StarRockRewardInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MonsterId     *uint32                `protobuf:"varint,1,opt,name=monster_id,json=monsterId" json:"monster_id,omitempty"`
	BaseConfId    *uint32                `protobuf:"varint,2,opt,name=base_conf_id,json=baseConfId" json:"base_conf_id,omitempty"`
	IsShiny       *bool                  `protobuf:"varint,3,opt,name=is_shiny,json=isShiny" json:"is_shiny,omitempty"`
	IsFantastic   *bool                  `protobuf:"varint,4,opt,name=is_fantastic,json=isFantastic" json:"is_fantastic,omitempty"`
	IsNightmare   *bool                  `protobuf:"varint,5,opt,name=is_nightmare,json=isNightmare" json:"is_nightmare,omitempty"`
	PetContentId  *int32                 `protobuf:"varint,6,opt,name=pet_content_id,json=petContentId" json:"pet_content_id,omitempty"`
	BelongSeason  *int32                 `protobuf:"varint,7,opt,name=belong_season,json=belongSeason" json:"belong_season,omitempty"`
	MixBlood      *int32                 `protobuf:"varint,8,opt,name=mix_blood,json=mixBlood" json:"mix_blood,omitempty"`
	Gender        *uint32                `protobuf:"varint,20,opt,name=gender" json:"gender,omitempty"`
	Height        *int32                 `protobuf:"varint,21,opt,name=height" json:"height,omitempty"`
	Weight        *int32                 `protobuf:"varint,22,opt,name=weight" json:"weight,omitempty"`
	Voice         *int32                 `protobuf:"varint,23,opt,name=voice" json:"voice,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StarRockRewardInfo) Reset() {
	*x = StarRockRewardInfo{}
	mi := &file_com_season_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StarRockRewardInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StarRockRewardInfo) ProtoMessage() {}

func (x *StarRockRewardInfo) ProtoReflect() protoreflect.Message {
	mi := &file_com_season_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StarRockRewardInfo.ProtoReflect.Descriptor instead.
func (*StarRockRewardInfo) Descriptor() ([]byte, []int) {
	return file_com_season_proto_rawDescGZIP(), []int{4}
}

func (x *StarRockRewardInfo) GetMonsterId() uint32 {
	if x != nil && x.MonsterId != nil {
		return *x.MonsterId
	}
	return 0
}

func (x *StarRockRewardInfo) GetBaseConfId() uint32 {
	if x != nil && x.BaseConfId != nil {
		return *x.BaseConfId
	}
	return 0
}

func (x *StarRockRewardInfo) GetIsShiny() bool {
	if x != nil && x.IsShiny != nil {
		return *x.IsShiny
	}
	return false
}

func (x *StarRockRewardInfo) GetIsFantastic() bool {
	if x != nil && x.IsFantastic != nil {
		return *x.IsFantastic
	}
	return false
}

func (x *StarRockRewardInfo) GetIsNightmare() bool {
	if x != nil && x.IsNightmare != nil {
		return *x.IsNightmare
	}
	return false
}

func (x *StarRockRewardInfo) GetPetContentId() int32 {
	if x != nil && x.PetContentId != nil {
		return *x.PetContentId
	}
	return 0
}

func (x *StarRockRewardInfo) GetBelongSeason() int32 {
	if x != nil && x.BelongSeason != nil {
		return *x.BelongSeason
	}
	return 0
}

func (x *StarRockRewardInfo) GetMixBlood() int32 {
	if x != nil && x.MixBlood != nil {
		return *x.MixBlood
	}
	return 0
}

func (x *StarRockRewardInfo) GetGender() uint32 {
	if x != nil && x.Gender != nil {
		return *x.Gender
	}
	return 0
}

func (x *StarRockRewardInfo) GetHeight() int32 {
	if x != nil && x.Height != nil {
		return *x.Height
	}
	return 0
}

func (x *StarRockRewardInfo) GetWeight() int32 {
	if x != nil && x.Weight != nil {
		return *x.Weight
	}
	return 0
}

func (x *StarRockRewardInfo) GetVoice() int32 {
	if x != nil && x.Voice != nil {
		return *x.Voice
	}
	return 0
}

type StarRockMonsterInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	GoldStar         *StarRockShellInfo     `protobuf:"bytes,1,opt,name=gold_star,json=goldStar" json:"gold_star,omitempty"`
	RedStar          *StarRockShellInfo     `protobuf:"bytes,2,opt,name=red_star,json=redStar" json:"red_star,omitempty"`
	GoldReward       *StarRockRewardInfo    `protobuf:"bytes,3,opt,name=gold_reward,json=goldReward" json:"gold_reward,omitempty"`
	RedReward        *StarRockRewardInfo    `protobuf:"bytes,4,opt,name=red_reward,json=redReward" json:"red_reward,omitempty"`
	StarColorLocked  *bool                  `protobuf:"varint,5,opt,name=star_color_locked,json=starColorLocked" json:"star_color_locked,omitempty"`
	StarResultColor  *StarRockColor         `protobuf:"varint,6,opt,name=star_result_color,json=starResultColor,enum=Next.StarRockColor" json:"star_result_color,omitempty"`
	StarColorHistory []StarRockColor        `protobuf:"varint,10,rep,name=star_color_history,json=starColorHistory,enum=Next.StarRockColor" json:"star_color_history,omitempty"`
	Activated        *bool                  `protobuf:"varint,11,opt,name=activated" json:"activated,omitempty"`
	RefreshBatchId   *uint64                `protobuf:"varint,40,opt,name=refresh_batch_id,json=refreshBatchId" json:"refresh_batch_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StarRockMonsterInfo) Reset() {
	*x = StarRockMonsterInfo{}
	mi := &file_com_season_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StarRockMonsterInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StarRockMonsterInfo) ProtoMessage() {}

func (x *StarRockMonsterInfo) ProtoReflect() protoreflect.Message {
	mi := &file_com_season_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StarRockMonsterInfo.ProtoReflect.Descriptor instead.
func (*StarRockMonsterInfo) Descriptor() ([]byte, []int) {
	return file_com_season_proto_rawDescGZIP(), []int{5}
}

func (x *StarRockMonsterInfo) GetGoldStar() *StarRockShellInfo {
	if x != nil {
		return x.GoldStar
	}
	return nil
}

func (x *StarRockMonsterInfo) GetRedStar() *StarRockShellInfo {
	if x != nil {
		return x.RedStar
	}
	return nil
}

func (x *StarRockMonsterInfo) GetGoldReward() *StarRockRewardInfo {
	if x != nil {
		return x.GoldReward
	}
	return nil
}

func (x *StarRockMonsterInfo) GetRedReward() *StarRockRewardInfo {
	if x != nil {
		return x.RedReward
	}
	return nil
}

func (x *StarRockMonsterInfo) GetStarColorLocked() bool {
	if x != nil && x.StarColorLocked != nil {
		return *x.StarColorLocked
	}
	return false
}

func (x *StarRockMonsterInfo) GetStarResultColor() StarRockColor {
	if x != nil && x.StarResultColor != nil {
		return *x.StarResultColor
	}
	return StarRockColor_STAR_ROCK_COLOR_NONE
}

func (x *StarRockMonsterInfo) GetStarColorHistory() []StarRockColor {
	if x != nil {
		return x.StarColorHistory
	}
	return nil
}

func (x *StarRockMonsterInfo) GetActivated() bool {
	if x != nil && x.Activated != nil {
		return *x.Activated
	}
	return false
}

func (x *StarRockMonsterInfo) GetRefreshBatchId() uint64 {
	if x != nil && x.RefreshBatchId != nil {
		return *x.RefreshBatchId
	}
	return 0
}

type SeasonBattleInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BoxInfo       *BoxMonsterInfo        `protobuf:"bytes,1,opt,name=box_info,json=boxInfo" json:"box_info,omitempty"`
	LineBallInfo  *LineBallMonsterInfo   `protobuf:"bytes,2,opt,name=line_ball_info,json=lineBallInfo" json:"line_ball_info,omitempty"`
	StarRockInfo  *StarRockMonsterInfo   `protobuf:"bytes,3,opt,name=star_rock_info,json=starRockInfo" json:"star_rock_info,omitempty"`
	SeasonPetInfo *SeasonPetInfo         `protobuf:"bytes,10,opt,name=season_pet_info,json=seasonPetInfo" json:"season_pet_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeasonBattleInfo) Reset() {
	*x = SeasonBattleInfo{}
	mi := &file_com_season_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeasonBattleInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeasonBattleInfo) ProtoMessage() {}

func (x *SeasonBattleInfo) ProtoReflect() protoreflect.Message {
	mi := &file_com_season_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeasonBattleInfo.ProtoReflect.Descriptor instead.
func (*SeasonBattleInfo) Descriptor() ([]byte, []int) {
	return file_com_season_proto_rawDescGZIP(), []int{6}
}

func (x *SeasonBattleInfo) GetBoxInfo() *BoxMonsterInfo {
	if x != nil {
		return x.BoxInfo
	}
	return nil
}

func (x *SeasonBattleInfo) GetLineBallInfo() *LineBallMonsterInfo {
	if x != nil {
		return x.LineBallInfo
	}
	return nil
}

func (x *SeasonBattleInfo) GetStarRockInfo() *StarRockMonsterInfo {
	if x != nil {
		return x.StarRockInfo
	}
	return nil
}

func (x *SeasonBattleInfo) GetSeasonPetInfo() *SeasonPetInfo {
	if x != nil {
		return x.SeasonPetInfo
	}
	return nil
}

var File_com_season_proto protoreflect.FileDescriptor

const file_com_season_proto_rawDesc = "" +
	"\n" +
	"\x10com_season.proto\x12\x04Next\x1a\x15com_battle_enum.proto\x1a\x0exls_enum.proto\"\x96\x05\n" +
	"\x0eBoxMonsterInfo\x12(\n" +
	"\bbox_type\x18\x01 \x01(\x0e2\r.Next.BoxTypeR\aboxType\x12\x19\n" +
	"\bis_shiny\x18\x02 \x01(\bR\aisShiny\x12!\n" +
	"\fis_fantastic\x18\x03 \x01(\bR\visFantastic\x12\x1e\n" +
	"\vbox_conf_id\x18\x04 \x01(\rR\tboxConfId\x12$\n" +
	"\x0epet_content_id\x18\x05 \x01(\x05R\fpetContentId\x12!\n" +
	"\fis_nightmare\x18\x06 \x01(\bR\visNightmare\x12#\n" +
	"\rbelong_season\x18\a \x01(\x05R\fbelongSeason\x12\x12\n" +
	"\x04name\x18\b \x01(\fR\x04name\x12\x1d\n" +
	"\n" +
	"monster_id\x18\t \x01(\rR\tmonsterId\x12;\n" +
	"\x0fpet_rarity_type\x18\n" +
	" \x01(\x0e2\x13.Next.PetRarityTypeR\rpetRarityType\x12A\n" +
	"\x11pet_mutation_type\x18\v \x01(\x0e2\x15.Next.PetMutationTypeR\x0fpetMutationType\x12\x1d\n" +
	"\n" +
	"pet_nature\x18\f \x01(\x05R\tpetNature\x12\x16\n" +
	"\x06gender\x18\r \x01(\rR\x06gender\x12\x16\n" +
	"\x06height\x18\x0e \x01(\x05R\x06height\x12\x16\n" +
	"\x06weight\x18\x0f \x01(\x05R\x06weight\x12\x14\n" +
	"\x05voice\x18\x10 \x01(\x05R\x05voice\x124\n" +
	"\bname_src\x18\x11 \x01(\x0e2\x19.dataconfig.PetNameSourceR\anameSrc\x12(\n" +
	"\x10refresh_batch_id\x18\x1e \x01(\x04R\x0erefreshBatchId\"\xd8\x01\n" +
	"\rSeasonPetInfo\x12!\n" +
	"\fis_nightmare\x18\x01 \x01(\bR\visNightmare\x12\x19\n" +
	"\bis_shiny\x18\x02 \x01(\bR\aisShiny\x12!\n" +
	"\fis_fantastic\x18\x03 \x01(\bR\visFantastic\x12\x1b\n" +
	"\tmix_blood\x18\x04 \x01(\x05R\bmixBlood\x12\x1f\n" +
	"\vdelete_time\x18\x05 \x01(\rR\n" +
	"deleteTime\x12(\n" +
	"\x10refresh_batch_id\x18\x14 \x01(\x04R\x0erefreshBatchId\"\xdc\x02\n" +
	"\x13LineBallMonsterInfo\x12\x19\n" +
	"\bis_shiny\x18\x01 \x01(\bR\aisShiny\x12!\n" +
	"\fis_fantastic\x18\x02 \x01(\bR\visFantastic\x12!\n" +
	"\fis_nightmare\x18\x03 \x01(\bR\visNightmare\x12$\n" +
	"\x0epet_content_id\x18\x04 \x01(\x05R\fpetContentId\x12#\n" +
	"\rbelong_season\x18\x05 \x01(\x05R\fbelongSeason\x12*\n" +
	"\x11pet_speciality_id\x18\x06 \x01(\x05R\x0fpetSpecialityId\x12&\n" +
	"\x0fpet_talent_rank\x18\a \x01(\x05R\rpetTalentRank\x12\x1b\n" +
	"\tmix_blood\x18\b \x01(\x05R\bmixBlood\x12(\n" +
	"\x10refresh_batch_id\x18\x14 \x01(\x04R\x0erefreshBatchId\"~\n" +
	"\x11StarRockShellInfo\x12\x1d\n" +
	"\n" +
	"monster_id\x18\x01 \x01(\rR\tmonsterId\x12 \n" +
	"\fbase_conf_id\x18\x02 \x01(\rR\n" +
	"baseConfId\x12(\n" +
	"\x10has_shiny_reward\x18\x03 \x01(\bR\x0ehasShinyReward\"\xfc\x02\n" +
	"\x12StarRockRewardInfo\x12\x1d\n" +
	"\n" +
	"monster_id\x18\x01 \x01(\rR\tmonsterId\x12 \n" +
	"\fbase_conf_id\x18\x02 \x01(\rR\n" +
	"baseConfId\x12\x19\n" +
	"\bis_shiny\x18\x03 \x01(\bR\aisShiny\x12!\n" +
	"\fis_fantastic\x18\x04 \x01(\bR\visFantastic\x12!\n" +
	"\fis_nightmare\x18\x05 \x01(\bR\visNightmare\x12$\n" +
	"\x0epet_content_id\x18\x06 \x01(\x05R\fpetContentId\x12#\n" +
	"\rbelong_season\x18\a \x01(\x05R\fbelongSeason\x12\x1b\n" +
	"\tmix_blood\x18\b \x01(\x05R\bmixBlood\x12\x16\n" +
	"\x06gender\x18\x14 \x01(\rR\x06gender\x12\x16\n" +
	"\x06height\x18\x15 \x01(\x05R\x06height\x12\x16\n" +
	"\x06weight\x18\x16 \x01(\x05R\x06weight\x12\x14\n" +
	"\x05voice\x18\x17 \x01(\x05R\x05voice\"\xeb\x03\n" +
	"\x13StarRockMonsterInfo\x124\n" +
	"\tgold_star\x18\x01 \x01(\v2\x17.Next.StarRockShellInfoR\bgoldStar\x122\n" +
	"\bred_star\x18\x02 \x01(\v2\x17.Next.StarRockShellInfoR\aredStar\x129\n" +
	"\vgold_reward\x18\x03 \x01(\v2\x18.Next.StarRockRewardInfoR\n" +
	"goldReward\x127\n" +
	"\n" +
	"red_reward\x18\x04 \x01(\v2\x18.Next.StarRockRewardInfoR\tredReward\x12*\n" +
	"\x11star_color_locked\x18\x05 \x01(\bR\x0fstarColorLocked\x12?\n" +
	"\x11star_result_color\x18\x06 \x01(\x0e2\x13.Next.StarRockColorR\x0fstarResultColor\x12A\n" +
	"\x12star_color_history\x18\n" +
	" \x03(\x0e2\x13.Next.StarRockColorR\x10starColorHistory\x12\x1c\n" +
	"\tactivated\x18\v \x01(\bR\tactivated\x12(\n" +
	"\x10refresh_batch_id\x18( \x01(\x04R\x0erefreshBatchId\"\x82\x02\n" +
	"\x10SeasonBattleInfo\x12/\n" +
	"\bbox_info\x18\x01 \x01(\v2\x14.Next.BoxMonsterInfoR\aboxInfo\x12?\n" +
	"\x0eline_ball_info\x18\x02 \x01(\v2\x19.Next.LineBallMonsterInfoR\flineBallInfo\x12?\n" +
	"\x0estar_rock_info\x18\x03 \x01(\v2\x19.Next.StarRockMonsterInfoR\fstarRockInfo\x12;\n" +
	"\x0fseason_pet_info\x18\n" +
	" \x01(\v2\x13.Next.SeasonPetInfoR\rseasonPetInfo"

var (
	file_com_season_proto_rawDescOnce sync.Once
	file_com_season_proto_rawDescData []byte
)

func file_com_season_proto_rawDescGZIP() []byte {
	file_com_season_proto_rawDescOnce.Do(func() {
		file_com_season_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_com_season_proto_rawDesc), len(file_com_season_proto_rawDesc)))
	})
	return file_com_season_proto_rawDescData
}

var file_com_season_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_com_season_proto_goTypes = []any{
	(*BoxMonsterInfo)(nil),      // 0: Next.BoxMonsterInfo
	(*SeasonPetInfo)(nil),       // 1: Next.SeasonPetInfo
	(*LineBallMonsterInfo)(nil), // 2: Next.LineBallMonsterInfo
	(*StarRockShellInfo)(nil),   // 3: Next.StarRockShellInfo
	(*StarRockRewardInfo)(nil),  // 4: Next.StarRockRewardInfo
	(*StarRockMonsterInfo)(nil), // 5: Next.StarRockMonsterInfo
	(*SeasonBattleInfo)(nil),    // 6: Next.SeasonBattleInfo
	(BoxType)(0),                // 7: Next.BoxType
	(PetRarityType)(0),          // 8: Next.PetRarityType
	(PetMutationType)(0),        // 9: Next.PetMutationType
	(PetNameSource)(0),          // 10: dataconfig.PetNameSource
	(StarRockColor)(0),          // 11: Next.StarRockColor
}
var file_com_season_proto_depIdxs = []int32{
	7,  // 0: Next.BoxMonsterInfo.box_type:type_name -> Next.BoxType
	8,  // 1: Next.BoxMonsterInfo.pet_rarity_type:type_name -> Next.PetRarityType
	9,  // 2: Next.BoxMonsterInfo.pet_mutation_type:type_name -> Next.PetMutationType
	10, // 3: Next.BoxMonsterInfo.name_src:type_name -> dataconfig.PetNameSource
	3,  // 4: Next.StarRockMonsterInfo.gold_star:type_name -> Next.StarRockShellInfo
	3,  // 5: Next.StarRockMonsterInfo.red_star:type_name -> Next.StarRockShellInfo
	4,  // 6: Next.StarRockMonsterInfo.gold_reward:type_name -> Next.StarRockRewardInfo
	4,  // 7: Next.StarRockMonsterInfo.red_reward:type_name -> Next.StarRockRewardInfo
	11, // 8: Next.StarRockMonsterInfo.star_result_color:type_name -> Next.StarRockColor
	11, // 9: Next.StarRockMonsterInfo.star_color_history:type_name -> Next.StarRockColor
	0,  // 10: Next.SeasonBattleInfo.box_info:type_name -> Next.BoxMonsterInfo
	2,  // 11: Next.SeasonBattleInfo.line_ball_info:type_name -> Next.LineBallMonsterInfo
	5,  // 12: Next.SeasonBattleInfo.star_rock_info:type_name -> Next.StarRockMonsterInfo
	1,  // 13: Next.SeasonBattleInfo.season_pet_info:type_name -> Next.SeasonPetInfo
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_com_season_proto_init() }
func file_com_season_proto_init() {
	if File_com_season_proto != nil {
		return
	}
	file_com_battle_enum_proto_init()
	file_xls_enum_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_com_season_proto_rawDesc), len(file_com_season_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_com_season_proto_goTypes,
		DependencyIndexes: file_com_season_proto_depIdxs,
		MessageInfos:      file_com_season_proto_msgTypes,
	}.Build()
	File_com_season_proto = out.File
	file_com_season_proto_goTypes = nil
	file_com_season_proto_depIdxs = nil
}
